// Generated by gencpp from file rover/DriveControls.msg
// DO NOT EDIT!


#ifndef ROVER_MESSAGE_DRIVECONTROLS_H
#define ROVER_MESSAGE_DRIVECONTROLS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rover/Vector3.h>
#include <rover/Vector3.h>

namespace rover
{
template <class ContainerAllocator>
struct DriveControls_
{
  typedef DriveControls_<ContainerAllocator> Type;

  DriveControls_()
    : header()
    , linear()
    , angular()  {
    }
  DriveControls_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear(_alloc)
    , angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::rover::Vector3_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::rover::Vector3_<ContainerAllocator>  _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::rover::DriveControls_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover::DriveControls_<ContainerAllocator> const> ConstPtr;

}; // struct DriveControls_

typedef ::rover::DriveControls_<std::allocator<void> > DriveControls;

typedef boost::shared_ptr< ::rover::DriveControls > DriveControlsPtr;
typedef boost::shared_ptr< ::rover::DriveControls const> DriveControlsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover::DriveControls_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover::DriveControls_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover::DriveControls_<ContainerAllocator1> & lhs, const ::rover::DriveControls_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.linear == rhs.linear &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover::DriveControls_<ContainerAllocator1> & lhs, const ::rover::DriveControls_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rover::DriveControls_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover::DriveControls_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover::DriveControls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover::DriveControls_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover::DriveControls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover::DriveControls_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover::DriveControls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09119d3b0067bd05b1a6696c168cebb3";
  }

  static const char* value(const ::rover::DriveControls_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09119d3b0067bd05ULL;
  static const uint64_t static_value2 = 0xb1a6696c168cebb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover::DriveControls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover/DriveControls";
  }

  static const char* value(const ::rover::DriveControls_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover::DriveControls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Vector3 linear\n"
"Vector3 angular\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rover/Vector3\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rover::DriveControls_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover::DriveControls_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveControls_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover::DriveControls_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover::DriveControls_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::rover::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::rover::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MESSAGE_DRIVECONTROLS_H
