// Generated by gencpp from file rover/GpsCoords.msg
// DO NOT EDIT!


#ifndef ROVER_MESSAGE_GPSCOORDS_H
#define ROVER_MESSAGE_GPSCOORDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rover
{
template <class ContainerAllocator>
struct GpsCoords_
{
  typedef GpsCoords_<ContainerAllocator> Type;

  GpsCoords_()
    : header()
    , valid(false)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , ground_speed(0.0)
    , satellites(0)
    , direction()  {
    }
  GpsCoords_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , ground_speed(0.0)
    , satellites(0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _ground_speed_type;
  _ground_speed_type ground_speed;

   typedef int32_t _satellites_type;
  _satellites_type satellites;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::rover::GpsCoords_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover::GpsCoords_<ContainerAllocator> const> ConstPtr;

}; // struct GpsCoords_

typedef ::rover::GpsCoords_<std::allocator<void> > GpsCoords;

typedef boost::shared_ptr< ::rover::GpsCoords > GpsCoordsPtr;
typedef boost::shared_ptr< ::rover::GpsCoords const> GpsCoordsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover::GpsCoords_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover::GpsCoords_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover::GpsCoords_<ContainerAllocator1> & lhs, const ::rover::GpsCoords_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.ground_speed == rhs.ground_speed &&
    lhs.satellites == rhs.satellites &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover::GpsCoords_<ContainerAllocator1> & lhs, const ::rover::GpsCoords_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rover::GpsCoords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover::GpsCoords_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover::GpsCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover::GpsCoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover::GpsCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover::GpsCoords_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover::GpsCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e7c7f9e823463c916e06e27876cc312";
  }

  static const char* value(const ::rover::GpsCoords_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e7c7f9e823463c9ULL;
  static const uint64_t static_value2 = 0x16e06e27876cc312ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover::GpsCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover/GpsCoords";
  }

  static const char* value(const ::rover::GpsCoords_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover::GpsCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool valid\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float64 ground_speed\n"
"int32 satellites\n"
"string direction\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rover::GpsCoords_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover::GpsCoords_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.ground_speed);
      stream.next(m.satellites);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsCoords_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover::GpsCoords_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover::GpsCoords_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "ground_speed: ";
    Printer<double>::stream(s, indent + "  ", v.ground_speed);
    s << indent << "satellites: ";
    Printer<int32_t>::stream(s, indent + "  ", v.satellites);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MESSAGE_GPSCOORDS_H
